services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py runserver 0.0.0.0:8000"
    disk:
      - name: data
        mountPath: /opt/render/project/src
