# Generated by Django 5.1.4 on 2024-12-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepie',
            old_name='receipe_description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='recepie',
            old_name='receipe_image',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='recepie',
            old_name='receipe_name',
            new_name='recipe_name',
        ),
    ]
